#!/usr/bin/env bash

mode=$1

log() {
  level=$1
  text=$2
  if [[ "$verbose" == "true" ]] || [[ "$level" == "info" ]]; then
    echo "time=$(date -u +"%Y-%m-%dT%H:%M:%SZ") level=$level user=$name msg=\"$text\""
  fi
}

generate_report() {
  # the generate-credential-report command returns before the actual report is
  # available for download
  while aws iam generate-credential-report | jq -e -r '.State != "COMPLETE"' >/dev/null; do
    echo ">>> waiting for new report..."
    sleep 5
  done

  aws iam get-credential-report | jq -r '.Content' | base64 -d >"$report"
}

detect_unused_keys() {
  number=$1
  active=$(echo "$user" | jq -r ".access_key_${number}_active")
  if [[ $active == true ]]; then
    last_used=$(echo "$user" | jq -r ".access_key_${number}_last_used_date")
    if [[ $last_used == "N/A" || "$(date -d "$last_used" +"%s")" -lt "$expiry" ]]; then
      # Unused key detected in the credentials report, inspecting user's keys with the API"
      inspect_user
    else
      log debug "access_key_$number is active and used: ($last_used)"
    fi
  fi
}

inspect_user() {
  for key in $(aws iam list-access-keys --user-name "$name" | jq -rc '.AccessKeyMetadata[] | select(.Status == "Active")'); do
    id=$(echo "$key" | jq -r ".AccessKeyId")
    last_used=$(aws iam get-access-key-last-used --access-key-id "$id" | jq -r '.AccessKeyLastUsed.LastUsedDate')
    if [[ "$last_used" == "null" ]]; then
      created=$(echo "$key" | jq -r ".CreateDate")
      if [[ "$(date -d "$created" +"%s")" -lt "$expiry" ]]; then
        log info "DELETE access_key $id never used on an old user ($created)"
        if ! aws iam delete-access-key --user-name "$name" --access-key-id "$id"; then
          log info "ERROR: failed to delete access_key $id"
        fi
      else
        log debug "access_key $id never used, but created recently ($created)"
      fi
    elif [[ "$(date -d "$last_used" +"%s")" -lt "$expiry" ]]; then
      log info "DELETE access_key $id unused recently ($last_used)\n"
      if ! aws iam delete-access-key --user-name "$name" --access-key-id "$id"; then
        log info "ERROR: failed to delete access_key $id"
      fi
    else
      log debug "access_key $id used recently ($last_used)"
    fi
  done
  user_inspected=true
}

if [[ "$mode" == "--verbose" ]]; then
  verbose=true
else
  verbose=false
fi

expiry=$(date +%s -d "45 days ago")
report=aws-report.csv

generate_report
headers="$(head -n1 "$report")"

for user in $(yq "$report" -ojson | jq -rc '.[]'); do
  name=$(echo "$user" | jq -r '.user')

  user_inspected=false
  counter=1
  while [[ "$headers" == *"access_key_$counter"* && "$user_inspected" == "false" ]]; do
    detect_unused_keys "$counter"
    ((counter++))
  done
done
